import type { LexemeBlockSource } from "./hpsg-adapter.js";

export const mvpLexemeSources = [
  {
    type: "be-lxm",
    base: "be",
    firstSingular: "am",
    thirdSingular: "is",
    nonThirdSingular: "are",
    pastSingular: "was",
    pastPlural: "were",
    presentParticiple: "being",
    pastParticiple: "been",
  },
  { type: "det-lxm", form: "a", count: "+" },
  { type: "det-lxm", form: "the" },
  { type: "pn-lxm", form: "john", reln: "named John" },
  { type: "pn-lxm", form: "mary", reln: "named Mary" },
  { type: "pn-lxm", form: "kim", reln: "named Kim" },
  {
    id: "i-pronoun",
    label: "I",
    lexemes: [
      {
        type: "pron-lxm",
        form: "I",
        case: "nom",
        agr: "1sing",
        per: "1st",
        num: "sg",
        index: "speaker",
        restr: [{ reln: "speaker", arg1: "speaker" }],
      },
      {
        type: "pron-lxm",
        form: "me",
        case: "acc",
        agr: "1sing",
        per: "1st",
        num: "sg",
        index: "speaker",
        restr: [{ reln: "speaker", arg1: "speaker" }],
      },
      {
        type: "det-lxm",
        form: "my",
      },
      {
        type: "pron-lxm",
        form: "myself",
        agr: "1sing",
        per: "1st",
        num: "sg",
        mode: "ana",
      },
    ],
  },
  {
    id: "you-pronoun",
    label: "you",
    lexemes: [
      {
        type: "pron-lxm",
        form: "you",
        case: "nom",
        agr: "agr-cat",
        per: "2nd",
        index: "addressee",
        restr: [{ reln: "addressee", arg1: "addressee" }],
      },
      {
        type: "pron-lxm",
        form: "you",
        case: "acc",
        agr: "agr-cat",
        per: "2nd",
        index: "addressee",
        restr: [{ reln: "addressee", arg1: "addressee" }],
      },
      {
        type: "det-lxm",
        form: "your",
      },
      {
        type: "pron-lxm",
        form: "yourself",
        agr: "agr-cat",
        per: "2nd",
        mode: "ana",
      },
    ],
  },
  {
    id: "she-pronoun",
    label: "she",
    lexemes: [
      {
        type: "pron-lxm",
        form: "she",
        case: "nom",
        agr: "3sing",
        per: "3rd",
        num: "sg",
        gend: "fem",
      },
      {
        type: "pron-lxm",
        form: "her",
        case: "acc",
        agr: "3sing",
        per: "3rd",
        num: "sg",
        gend: "fem",
      },
      {
        type: "det-lxm",
        form: "her",
      },
      {
        type: "pron-lxm",
        form: "herself",
        agr: "3sing",
        per: "3rd",
        num: "sg",
        gend: "fem",
        mode: "ana",
      },
    ],
  },
  { type: "cntn-lxm", singular: "girl", plural: "girls", reln: "girl" },
  { type: "cntn-lxm", singular: "boy", plural: "boys", reln: "boy" },
  { type: "cntn-lxm", singular: "telescope", plural: "telescopes", reln: "telescope" },
  { type: "cntn-lxm", singular: "book", plural: "books", reln: "book" },
  { type: "massn-lxm", form: "water", reln: "water" },
  { type: "adj-lxm", form: "big", reln: "big" },
  { type: "adj-lxm", form: "small", reln: "small" },
  { type: "adv-lxm", form: "quickly" },
  { type: "adv-lxm", form: "slowly" },
  {
    type: "siv-lxm",
    base: "walk",
    thirdSingular: "walks",
    presentParticiple: "walking",
    pastTense: "walked",
    pastParticiple: "walked",
    reln: "walk",
  },
  {
    type: "piv-lxm",
    base: "go",
    thirdSingular: "goes",
    presentParticiple: "going",
    pastTense: "went",
    pastParticiple: "gone",
    reln: "go",
    prepositionForm: "to-form",
  },
  {
    type: "stv-lxm",
    base: "see",
    thirdSingular: "sees",
    presentParticiple: "seeing",
    pastTense: "saw",
    pastParticiple: "seen",
    reln: "see",
  },
  {
    type: "stv-lxm",
    base: "drink",
    thirdSingular: "drinks",
    presentParticiple: "drinking",
    pastTense: "drank",
    pastParticiple: "drunk",
    reln: "drink",
  },
  {
    type: "dtv-lxm",
    base: "give",
    thirdSingular: "gives",
    presentParticiple: "giving",
    pastTense: "gave",
    pastParticiple: "given",
    reln: "give",
  },
  {
    id: "send-verb",
    label: "send",
    lexemes: [
      {
        type: "dtv-lxm",
        base: "send",
        thirdSingular: "sends",
        presentParticiple: "sending",
        pastTense: "sent",
        pastParticiple: "sent",
        reln: "send",
      },
      {
        type: "ptv-lxm",
        base: "send",
        thirdSingular: "sends",
        presentParticiple: "sending",
        pastTense: "sent",
        pastParticiple: "sent",
        reln: "send",
        prepositionForm: "to-form",
      },
    ],
  },
  { type: "argmkp-lxm", form: "to" },
  { type: "argmkp-lxm", form: "of" },
  { type: "predp-lxm", form: "in", reln: "in", mod: "nom" },
  { type: "predp-lxm", form: "near", reln: "near", mod: "nom" },
] satisfies LexemeBlockSource[];
